"""
senda.workflow.run
CLI entry point for senda-slurm.

Generates a set of SLURM scripts and a top-level submit.sh that chains the
full senda workflow with --dependency=afterok so that downstream jobs are
cancelled on upstream failure:

  senda-param   (optional, skip with --skip-param)
      -> afterok
  senda-complex
      -> afterok
  senda-launch  (runs senda-sim setup, then sbatch each replica's run_gpu)
      ->
  [run_gpu x N replicas - parallel GPU jobs, each chains NVT chunks internally]

Usage:
    senda-slurm --config config.yaml
    senda-slurm --config config.yaml --skip-param
    senda-slurm --config config.yaml --out-dir workflow/
"""

from __future__ import annotations

import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# SLURM header builder
# ---------------------------------------------------------------------------

def _header(
    job_name:   str,
    out:        str,
    err:        str,
    spec:       dict,
    modules:    list[str] | None = None,
    senda_env:  str = "",
) -> str:
    """Build the SBATCH preamble for a SLURM script."""
    lines = [
        "#!/bin/bash",
        f"#SBATCH --time={spec['time']}",
        f"#SBATCH --ntasks={spec.get('ntasks', 1)}",
        f"#SBATCH --cpus-per-task={spec.get('cpus-per-task', 1)}",
    ]
    if spec.get("mem"):
        lines.append(f"#SBATCH --mem={spec['mem']}")
    if spec.get("gres"):
        lines.append(f"#SBATCH --gres={spec['gres']}")
    lines += [
        f"#SBATCH --partition={spec['partition']}",
        f"#SBATCH --account={spec['account']}",
        f"#SBATCH --job-name={job_name}",
        f"#SBATCH --output={out}",
        f"#SBATCH --error={err}",
        "",
    ]
    for mod in (modules or []):
        lines.append(f"module load {mod}")
    if senda_env:
        lines.append(senda_env)
    lines += ["", "set -euo pipefail", 'cd "${SLURM_SUBMIT_DIR}"', ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Individual SLURM script generators
# ---------------------------------------------------------------------------

def _param_script(slurm: dict, config: str, out_dir: str) -> str:
    spec      = {**slurm["cpu"], "account": slurm["account"]}
    senda_env = slurm.get("senda_env", "") or ""
    head      = _header(
        job_name  = "senda_param",
        out       = f"{out_dir}/senda_param-%j.out",
        err       = f"{out_dir}/senda_param-%j.err",
        spec      = spec,
        modules   = [slurm["amber_module"]],
        senda_env = senda_env,
    )
    return head + f"senda-param --config {config}\n"


def _complex_script(slurm: dict, config: str, out_dir: str) -> str:
    spec      = {**slurm["cpu"], "account": slurm["account"]}
    senda_env = slurm.get("senda_env", "") or ""
    head      = _header(
        job_name  = "senda_complex",
        out       = f"{out_dir}/senda_complex-%j.out",
        err       = f"{out_dir}/senda_complex-%j.err",
        spec      = spec,
        senda_env = senda_env,
    )
    return head + f"senda-complex --config {config}\n"


def _launch_script(slurm: dict, config: str, out_dir: str, force: bool = False) -> str:
    spec      = {**slurm["cpu"], "account": slurm["account"]}
    senda_env = slurm.get("senda_env", "") or ""
    head      = _header(
        job_name  = "senda_launch",
        out       = f"{out_dir}/senda_launch-%j.out",
        err       = f"{out_dir}/senda_launch-%j.err",
        spec      = spec,
        senda_env = senda_env,
    )
    force_flag = " --force" if force else ""
    body = f"""\
senda-sim --config {config} setup{force_flag}
senda-sim --config {config} submit
"""
    return head + body


def _submit_script(skip_param: bool, out_dir: str) -> str:
    lines = [
        "#!/bin/bash",
        "# Generated by senda-slurm. Run once from the project root:",
        f"#   bash {out_dir}/submit.sh",
        "set -euo pipefail",
        'cd "$(dirname "${BASH_SOURCE[0]}")/.."',
        "",
        'echo "=== senda workflow submission ==="',
        "",
    ]

    if skip_param:
        lines += [
            f'complex_jid=$(sbatch --parsable {out_dir}/senda_complex.sh)',
            'echo "  senda-complex -> job $complex_jid"',
            "",
            f'launch_jid=$(sbatch --parsable --dependency=afterok:$complex_jid {out_dir}/senda_launch.sh)',
            'echo "  senda-launch  -> job $launch_jid"',
            "",
            'echo ""',
            'echo "Monitor : squeue -j $complex_jid,$launch_jid"',
            'echo "Cancel  : scancel $complex_jid $launch_jid"',
        ]
    else:
        lines += [
            f'param_jid=$(sbatch --parsable {out_dir}/senda_param.sh)',
            'echo "  senda-param   -> job $param_jid"',
            "",
            f'complex_jid=$(sbatch --parsable --dependency=afterok:$param_jid {out_dir}/senda_complex.sh)',
            'echo "  senda-complex -> job $complex_jid"',
            "",
            f'launch_jid=$(sbatch --parsable --dependency=afterok:$complex_jid {out_dir}/senda_launch.sh)',
            'echo "  senda-launch  -> job $launch_jid"',
            "",
            'echo ""',
            'echo "Monitor : squeue -j $param_jid,$complex_jid,$launch_jid"',
            'echo "Cancel  : scancel $param_jid $complex_jid $launch_jid"',
        ]

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------

def _require_keys(spec: dict, keys: list[str], section: str) -> None:
    missing = [k for k in keys if not spec.get(k)]
    if missing:
        sys.exit(
            f"Error: slurm.{section} is missing required keys: {missing}\n"
            f"Add them to the slurm section of your config.yaml."
        )


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(
        description=(
            "Generate SLURM scripts for the full senda workflow.\n"
            "Stages chain with --dependency=afterok; replicas run in parallel."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--config", required=True, metavar="CONFIG",
                        help="Path to senda config.yaml")
    parser.add_argument("--skip-param", action="store_true",
                        help="Omit senda-param (use when parameters already exist)")
    parser.add_argument("--force", action="store_true",
                        help="Pass --force to senda-sim setup (overwrite existing replica dirs)")
    parser.add_argument("--out-dir", default="workflow", metavar="DIR",
                        help="Directory for generated scripts (default: workflow/)")
    args = parser.parse_args()

    config_path = Path(args.config)
    if not config_path.exists():
        sys.exit(f"Error: config not found: {config_path}")

    try:
        import yaml
    except ImportError:
        sys.exit("pyyaml is required: pip install pyyaml")

    with open(config_path) as fh:
        cfg = yaml.safe_load(fh) or {}

    slurm = cfg.get("slurm") or {}
    if not slurm:
        sys.exit("Error: missing 'slurm:' section in config")

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Validate required slurm sections
    if not slurm.get("account"):
        sys.exit("Error: slurm.account is required")
    if not slurm.get("cpu"):
        sys.exit("Error: slurm.cpu section is required")
    _require_keys(slurm["cpu"], ["time", "partition"], "cpu")
    if not slurm.get("gpu"):
        sys.exit("Error: slurm.gpu section is required")
    _require_keys(slurm["gpu"], ["time", "partition", "gres"], "gpu")
    if not args.skip_param and not slurm.get("amber_module"):
        sys.exit("Error: slurm.amber_module is required for senda-param")

    # Config path relative to project root (where submit.sh will be run from)
    config_rel = str(config_path)

    def _write_exe(path: Path, content: str) -> None:
        path.write_text(content)
        path.chmod(0o755)

    # Generate scripts
    if not args.skip_param:
        _write_exe(out_dir / "senda_param.sh",
                   _param_script(slurm, config_rel, str(out_dir)))

    _write_exe(out_dir / "senda_complex.sh",
               _complex_script(slurm, config_rel, str(out_dir)))
    _write_exe(out_dir / "senda_launch.sh",
               _launch_script(slurm, config_rel, str(out_dir), force=args.force))
    _write_exe(out_dir / "submit.sh",
               _submit_script(args.skip_param, str(out_dir)))

    # Report
    print(f"Generated in {out_dir}/:")
    if not args.skip_param:
        print(f"  senda_param.sh   -ligand parameterization  [{slurm['cpu']['time']}]")
    print(f"  senda_complex.sh -Michaelis complex prep    [{slurm['cpu']['time']}]")
    print(f"  senda_launch.sh  -sim setup + replica sbatch [{slurm['cpu']['time']}]")
    print(f"  submit.sh        -top-level submission script")
    print()
    if args.skip_param:
        print("Ligand parameterization skipped (--skip-param).")
        print()
    print(f"Submit with: bash {out_dir}/submit.sh")
