"""
senda.workflow.run
CLI entry point for senda-slurm.

Generates a set of SLURM scripts and a top-level submit.sh that chains the
full senda workflow with --dependency=afterok so that downstream jobs are
cancelled on upstream failure:

  senda-param   (optional, skip with --skip-param)
      -> afterok
  senda-complex
      -> afterok
  senda-launch  (runs senda-sim setup, then sbatch each replica's run_gpu)
      ->
  [run_gpu x N replicas - parallel GPU jobs, each chains NVT chunks internally]

Usage:
    senda-slurm --config config.yaml
    senda-slurm --config config.yaml --skip-param
    senda-slurm --config config.yaml --out-dir workflow/
"""

from __future__ import annotations

import sys
from pathlib import Path

from senda.config import sbatch_lines


# ---------------------------------------------------------------------------
# SLURM header builder
# ---------------------------------------------------------------------------

def _header(
    job_name:   str,
    out:        str,
    err:        str,
    spec:       dict,
    modules:    list[str] | None = None,
    senda_env:  str = "",
) -> str:
    """Build the SBATCH preamble for a SLURM script. Every SLURM field in
    *spec* (time, ntasks, partition, account, qos, mem, gres, ...) is
    optional -- whatever's present is emitted, whatever's absent is
    skipped, so this works regardless of which fields a given cluster
    actually needs."""
    lines = [
        "#!/bin/bash",
        sbatch_lines(spec, reserved=set()),
        f"#SBATCH --job-name={job_name}",
        f"#SBATCH --output={out}",
        f"#SBATCH --error={err}",
        "",
    ]
    for mod in (modules or []):
        lines.append(f"module load {mod}")
    if senda_env:
        lines.append(senda_env)
    lines += ["", "set -euo pipefail", 'cd "${SLURM_SUBMIT_DIR}"', ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Individual SLURM script generators
# ---------------------------------------------------------------------------

def _cpu_spec(slurm: dict) -> dict:
    """slurm.cpu if set, else fall back to slurm.gpu -- for GPU-only
    clusters with no separate CPU partition, so param/complex/launch
    jobs don't need a redundant, duplicated cpu: block."""
    return slurm.get("cpu") or slurm["gpu"]


def _param_script(slurm: dict, config: str, out_dir: str) -> str:
    spec      = {**_cpu_spec(slurm), "account": slurm.get("account", "")}
    senda_env = slurm.get("senda_env", "") or ""
    head      = _header(
        job_name  = "senda_param",
        out       = f"{out_dir}/senda_param-%j.out",
        err       = f"{out_dir}/senda_param-%j.err",
        spec      = spec,
        modules   = [slurm["amber_module"]],
        senda_env = senda_env,
    )
    return head + f"senda-param --config {config}\n"


def _complex_script(slurm: dict, config: str, out_dir: str) -> str:
    spec      = {**_cpu_spec(slurm), "account": slurm.get("account", "")}
    senda_env = slurm.get("senda_env", "") or ""
    head      = _header(
        job_name  = "senda_complex",
        out       = f"{out_dir}/senda_complex-%j.out",
        err       = f"{out_dir}/senda_complex-%j.err",
        spec      = spec,
        senda_env = senda_env,
    )
    return head + f"senda-complex --config {config}\n"


def _launch_script(slurm: dict, config: str, out_dir: str, force: bool = False) -> str:
    spec      = {**_cpu_spec(slurm), "account": slurm.get("account", "")}
    senda_env = slurm.get("senda_env", "") or ""
    head      = _header(
        job_name  = "senda_launch",
        out       = f"{out_dir}/senda_launch-%j.out",
        err       = f"{out_dir}/senda_launch-%j.err",
        spec      = spec,
        senda_env = senda_env,
    )
    force_flag = " --force" if force else ""
    body = f"""\
senda-sim --config {config} setup{force_flag}
senda-sim --config {config} submit
"""
    return head + body


def _submit_script(skip_param: bool, out_dir: str) -> str:
    lines = [
        "#!/bin/bash",
        "# Generated by senda-slurm. Run once from the project root:",
        f"#   bash {out_dir}/submit.sh",
        "set -euo pipefail",
        'cd "$(dirname "${BASH_SOURCE[0]}")/.."',
        "",
        'echo "=== senda workflow submission ==="',
        "",
    ]

    if skip_param:
        lines += [
            f'complex_jid=$(sbatch --parsable {out_dir}/senda_complex.sh)',
            'echo "  senda-complex -> job $complex_jid"',
            "",
            f'launch_jid=$(sbatch --parsable --dependency=afterok:$complex_jid {out_dir}/senda_launch.sh)',
            'echo "  senda-launch  -> job $launch_jid"',
            "",
            'echo ""',
            'echo "Monitor : squeue -j $complex_jid,$launch_jid"',
            'echo "Cancel  : scancel $complex_jid $launch_jid"',
        ]
    else:
        lines += [
            f'param_jid=$(sbatch --parsable {out_dir}/senda_param.sh)',
            'echo "  senda-param   -> job $param_jid"',
            "",
            f'complex_jid=$(sbatch --parsable --dependency=afterok:$param_jid {out_dir}/senda_complex.sh)',
            'echo "  senda-complex -> job $complex_jid"',
            "",
            f'launch_jid=$(sbatch --parsable --dependency=afterok:$complex_jid {out_dir}/senda_launch.sh)',
            'echo "  senda-launch  -> job $launch_jid"',
            "",
            'echo ""',
            'echo "Monitor : squeue -j $param_jid,$complex_jid,$launch_jid"',
            'echo "Cancel  : scancel $param_jid $complex_jid $launch_jid"',
        ]

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(
        description=(
            "Generate SLURM scripts for the full senda workflow.\n"
            "Stages chain with --dependency=afterok; replicas run in parallel."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--config", required=True, metavar="CONFIG",
                        help="Path to senda config.yaml")
    parser.add_argument("--skip-param", action="store_true",
                        help="Omit senda-param (use when parameters already exist)")
    parser.add_argument("--force", action="store_true",
                        help="Pass --force to senda-sim setup (overwrite existing replica dirs)")
    parser.add_argument("--out-dir", default="workflow", metavar="DIR",
                        help="Directory for generated scripts (default: workflow/)")
    args = parser.parse_args()

    config_path = Path(args.config)
    if not config_path.exists():
        sys.exit(f"Error: config not found: {config_path}")

    try:
        import yaml
    except ImportError:
        sys.exit("pyyaml is required: pip install pyyaml")

    with open(config_path) as fh:
        cfg = yaml.safe_load(fh) or {}

    slurm = cfg.get("slurm") or {}
    if not slurm:
        sys.exit("Error: missing 'slurm:' section in config")

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # slurm.gpu must exist as a section (run_gpu/NVT jobs need a resource
    # spec to build from -- and slurm.cpu falls back to it when absent),
    # but no individual field within it is required: different clusters
    # need different subsets of partition/gres/account/qos/etc, and
    # whichever ones are present just get emitted, sbatch complains
    # directly if something a cluster truly needs is still missing.
    if not slurm.get("gpu"):
        sys.exit("Error: slurm.gpu section is required")
    if not args.skip_param and not slurm.get("amber_module"):
        sys.exit("Error: slurm.amber_module is required for senda-param")

    # Config path relative to project root (where submit.sh will be run from)
    config_rel = str(config_path)

    def _write_exe(path: Path, content: str) -> None:
        path.write_text(content)
        path.chmod(0o755)

    # Generate scripts
    if not args.skip_param:
        _write_exe(out_dir / "senda_param.sh",
                   _param_script(slurm, config_rel, str(out_dir)))

    _write_exe(out_dir / "senda_complex.sh",
               _complex_script(slurm, config_rel, str(out_dir)))
    _write_exe(out_dir / "senda_launch.sh",
               _launch_script(slurm, config_rel, str(out_dir), force=args.force))
    _write_exe(out_dir / "submit.sh",
               _submit_script(args.skip_param, str(out_dir)))

    # Report
    cpu_time = _cpu_spec(slurm)["time"]
    print(f"Generated in {out_dir}/:")
    if not args.skip_param:
        print(f"  senda_param.sh   -ligand parameterization  [{cpu_time}]")
    print(f"  senda_complex.sh -Michaelis complex prep    [{cpu_time}]")
    print(f"  senda_launch.sh  -sim setup + replica sbatch [{cpu_time}]")
    print(f"  submit.sh        -top-level submission script")
    print()
    if args.skip_param:
        print("Ligand parameterization skipped (--skip-param).")
        print()
    print(f"Submit with: bash {out_dir}/submit.sh")
