[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "senda"
dynamic = ["version"]
description = "Modular Python framework for enzyme QM/MM free energy calculations."
requires-python = ">=3.9"
dependencies = ["pyyaml", "numpy", "biopython"]

[project.optional-dependencies]
rdkit    = ["rdkit"]
analysis = ["scipy", "matplotlib", "pytraj"]
qmmm     = ["parmed", "pytraj"]

[project.scripts]
senda-param       = "senda.ligand_parameters.run:main"
senda-complex     = "senda.michaelis_complex.run:main"
senda-sim         = "senda.simulation.run:main"
senda-slurm       = "senda.workflow.run:main"
senda-analyse     = "senda.analysis.run:main"
senda-qmmm        = "senda.qmmm.string.run:main"
senda-integration = "senda.integration.run:main"

[tool.setuptools.dynamic]
version = {attr = "senda.__version__"}

[tool.setuptools.packages.find]
include = ["senda*"]
