"""
senda.simulation.templates
AMBER input file and SLURM/local script templates.

All placeholders use the __KEY__ convention; replaced by fill().
"""

import json

# ---------------------------------------------------------------------------
# AMBER input files
# ---------------------------------------------------------------------------

MIN = """\
Initial minimization
 &cntrl
  imin   = 1,
  maxcyc = __MAXCYC__,
  ncyc   = __NCYC__,
  ntb    = 1,
  ntxo   = 1,
  cut    = __CUT__,
  iwrap  = 1,__NMROPT__
 /
__WTBLOCK__"""

HEAT = """\
Stage 2 heating on GPU 1K to __TEMP__K
 &cntrl
  imin=0, irest=0, ntx=1,
  nstlim=__NSTLIM__, dt=__DT__,
  ntb=1, ntp=0,
  ntc=2, ntf=2, ntt=3,
  ntpr=1000, ntwr=1000, ntwx=1000,
  ntr=1,
  restraintmask='__RESTRAINTMASK__',
  restraint_wt=__RESTRAINT_WT__,
  cut=10, gamma_ln=5.0,
  nmropt=1, iwrap=1, ntxo=1,
 /

&wt type='TEMP0', istep1=0, istep2=__RAMPEND__,
  value1=1.0, value2=__TEMP__
/
&wt type='END'/
__DISANG__"""

EQUIL_NPT = """\
equilibration cycle __CYCLE__ (restrained NPT)
 &cntrl
  imin=0, irest=1, ntx=5,
  nstlim=__NSTLIM__, dt=__DT__,
  ntb=2, ntp=1, barostat=2,
  ntc=2, ntf=2, ntt=3,
  tempi=__TEMP__, temp0=__TEMP__,
  ntpr=1000, ntwx=1000,
  ntr=1,
  restraintmask='__RESTRAINTMASK__',
  restraint_wt=__WT__,
  cut=10, gamma_ln=5.0,
  iwrap=1, ntxo=1,__NMROPT__
 /
__WTDISANG__"""

EQUIL_NVT = """\
equilibration cycle 6 (unrestrained NVT)
 &cntrl
  imin=0, irest=1, ntx=5,
  nstlim=__NSTLIM__, dt=__DT__,
  ntb=1, ntp=0,
  ntc=2, ntf=2, ntt=3,
  tempi=__TEMP__, temp0=__TEMP__,
  ntpr=1000, ntwx=1000,
  cut=10, gamma_ln=5.0,
  iwrap=1, ntxo=1,__NMROPT__
 /
__WTDISANG__"""

PROD = """\
NVT production
 &cntrl
  imin=0, irest=1, ntx=5,
  nstlim=__NSTLIM__, dt=__DT__,
  ntb=1, ntp=0,
  ntc=2, ntf=2, ntt=3,
  tempi=__TEMP__, temp0=__TEMP__,
  ntpr=__NTPR__, ntwx=__NTWX__, ntwr=__NTWR__,
  cut=10, gamma_ln=1.0,
  iwrap=1, ntxo=1,__NMROPT__
 /
__WTDISANG__"""

HMR_CCPTRAJ = """\
parm structure.parm7
hmassrepartition dowater
parmwrite out structure_HMR.parm7
quit
"""

# Two-pass tleap block for the SPLIT ion-placement method.
# Placeholders __PDB_NAME__ and __MOLARITY__ are filled at setup time;
# ${NWATER}, ${Q}, etc. are bash variables expanded at job runtime.
# Ref: Machado & Pantano, J. Chem. Theory Comput. 2020, doi:10.1021/acs.jctc.9b00953
SPLIT_LEAP_BLOCK = """\
# Pass 1: count solute charge and solvation waters
tleap -f leap_count > leap_count.log 2>&1

Q=$(grep "Total unperturbed charge" leap_count.log | awk '{printf "%.0f", $NF}')
NWATER_SOL=$(grep "Added [0-9]* residues" leap_count.log | tail -1 | awk '{print $2}')
NWATER_XTAL=$(awk '($1=="ATOM"||$1=="HETATM") && ($4=="HOH"||$4=="WAT") && ($3=="O"||$3=="OW")' \\
              __PDB_NAME__ | wc -l | tr -d ' ')
NWATER=$((NWATER_SOL + NWATER_XTAL))

# SPLIT method: No=Nw*Co/56; N+=ceil(No-Q/2); N-=ceil(No+Q/2)
NPOS=$(awk "BEGIN { x=${NWATER}*__MOLARITY__/56 - ${Q}/2.0; printf \\"%d\\", (x>int(x))?int(x)+1:int(x) }")
NNEG=$(awk "BEGIN { x=${NWATER}*__MOLARITY__/56 + ${Q}/2.0; printf \\"%d\\", (x>int(x))?int(x)+1:int(x) }")

sed -e "s/NPOS/${NPOS}/g" \\
    -e "s/NNEG/${NNEG}/g" \\
    leap_structure_tmpl > leap_structure
rm leap_count.log

# Pass 2: build solvated system with correct NaCl concentration
tleap -f leap_structure"""

# ---------------------------------------------------------------------------
# NMR restraint script generator
# ---------------------------------------------------------------------------

# Template for the runtime restrainer.py script.
# __RESTRAINTS__ is replaced with a JSON list of restraint definitions.
_RESTRAINER_TEMPLATE = '''\
#!/usr/bin/env python3
# Auto-generated by senda. Edit restraints in the config file.
import re
from pathlib import Path

PRMTOP     = Path("00_prep/structure.parm7")
RESTRAINTS = __RESTRAINTS__


def _read_section(text, flag):
    pat = rf\'%FLAG {flag}\\s*\\n%FORMAT\\(([^)]+)\\)\\s*\\n(.*?)(?=%FLAG|\\Z)\'
    m = re.search(pat, text, re.DOTALL)
    if not m:
        raise ValueError(f"Section {flag!r} not found in prmtop")
    width = int(re.match(r\'\\d+[aAiIfFeE](\\d+)\', m.group(1)).group(1))
    items = []
    for line in m.group(2).splitlines():
        for i in range(0, len(line), width):
            field = line[i:i + width].strip()
            if field:
                items.append(field)
    return items


text       = PRMTOP.read_text()
atom_names = _read_section(text, "ATOM_NAME")
res_labels = _read_section(text, "RESIDUE_LABEL")
res_ptrs   = [int(x) for x in _read_section(text, "RESIDUE_POINTER")]
n_atoms    = len(atom_names)
n_res      = len(res_labels)

# (start_0based, [atom_name, ...]) for each residue
res_slices = []
for ri in range(n_res):
    start = res_ptrs[ri] - 1
    end   = res_ptrs[ri + 1] - 1 if ri + 1 < n_res else n_atoms
    res_slices.append((start, atom_names[start:end]))


def _atom_indices(res_name, atom_name):
    """Return list of 1-based AMBER atom indices for atom_name in every res_name residue."""
    results = []
    for ri, (start, seg) in enumerate(res_slices):
        if res_labels[ri] != res_name:
            continue
        if atom_name not in seg:
            raise ValueError(f"Atom {atom_name!r} not found in {res_name} residue (0-based {ri})")
        results.append(start + seg.index(atom_name) + 1)
    if not results:
        raise ValueError(f"Residue {res_name!r} not found in topology")
    return results


def _write_rst(f, idx, r):
    """Write one &rst block. idx is a list of 1-based AMBER atom indices (2, 3, or 4)."""
    pad = list(idx) + [0] * (4 - len(idx))
    f.write("&rst\\n")
    f.write(f"iat={pad[0]}, {pad[1]}, {pad[2]}, {pad[3]},\\n")
    f.write(f"r1={r[\'r1\']}, r2={r[\'r2\']}, r3={r[\'r3\']}, r4={r[\'r4\']}\\n")
    f.write(f"rk2={r[\'rk2\']}, rk3={r[\'rk3\']}\\n")
    f.write("/\\n\\n")


with open("restr", "w") as f:
    for restr in RESTRAINTS:
        specs  = restr["atoms"]   # list of {"residue": ..., "name": ...}
        resns  = [s["residue"] for s in specs]
        anames = [s["name"]    for s in specs]

        if len(set(resns)) == 1:
            # All atoms in the same residue type:
            # generate one &rst block per instance of that residue in the topology.
            atom_lists = [_atom_indices(resns[0], an) for an in anames]
            n_inst = len(atom_lists[0])
            for inst_i in range(n_inst):
                idx = [lst[inst_i] for lst in atom_lists]
                _write_rst(f, idx, restr)
        else:
            # Cross-residue: pick one atom per spec.
            # Use "index" key (0-based) to disambiguate when multiple residues match.
            idx = []
            for spec in specs:
                candidates = _atom_indices(spec["residue"], spec["name"])
                pick = spec.get("index", 0)
                if pick >= len(candidates):
                    raise ValueError(
                        f"index={pick} out of range for {spec[\'residue\']} "
                        f"({len(candidates)} instance(s) found)"
                    )
                idx.append(candidates[pick])
            _write_rst(f, idx, restr)

print(f"restr written ({len(RESTRAINTS)} restraint definition(s))")
'''


def make_restrainer(nmr_restraints: list[dict]) -> str:
    """
    Generate a restrainer.py script that writes an AMBER NMR DISANG file at
    job time, after the topology is built by tleap.

    *nmr_restraints* is the list of restraint dicts from the config
    ``amber_simulator.restraints.nmr`` section.
    """
    restr_json = json.dumps(nmr_restraints, indent=4)
    return _RESTRAINER_TEMPLATE.replace("__RESTRAINTS__", restr_json)


# ---------------------------------------------------------------------------
# Cluster (SLURM) run scripts
# ---------------------------------------------------------------------------

RUN_GPU_HEADER = """\
#!/bin/bash
#SBATCH --time=__WALLTIME__
#SBATCH --nodes=1
#SBATCH --ntasks=__NTASKS__
#SBATCH --gres=__GRES__
#SBATCH --partition=__PARTITION__
#SBATCH --job-name=__JOBNAME__
#SBATCH --account=__ACCOUNT__
#SBATCH --output=__REPLICA_DIR__/slurm-%j.out
#SBATCH --error=__REPLICA_DIR__/slurm-%j.err

module load __MODULE__

set -euo pipefail

DIR=__REPLICA_DIR__
"""

NVT_CLUSTER_HEADER = """\
#!/bin/bash
#SBATCH --time=__WALLTIME__
#SBATCH --nodes=1
#SBATCH --ntasks=__NTASKS__
#SBATCH --gres=__GRES__
#SBATCH --partition=__PARTITION__
#SBATCH --job-name=__JOBNAME__
#SBATCH --account=__ACCOUNT__
#SBATCH --output=__JOBNAME__-%j.out
#SBATCH --error=__JOBNAME__-%j.err

module load __MODULE__

set -euo pipefail

cd "${SLURM_SUBMIT_DIR}"
DIR=$(pwd)
"""

# ---------------------------------------------------------------------------
# Local (single GPU workstation) run scripts
# ---------------------------------------------------------------------------

RUN_LOCAL_HEADER = """\
#!/bin/bash
# Master run script: stages 00-03 + launch 04_NVT on a local GPU workstation.
# Usage:
#   bash run_local                          # foreground
#   nohup bash run_local > run.log 2>&1 &   # background
__AMBER_SETUP__

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
"""

NVT_LOCAL_HEADER = """\
#!/bin/bash
# NVT production: chunks __START__ to __END__ of __TOTAL__.
__AMBER_SETUP__

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"
"""

# ---------------------------------------------------------------------------
# Shared simulation body (stages 00-04) - used by both cluster and local
# ---------------------------------------------------------------------------

RUN_BODY = """\

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }

# -- 00_prep ------------------------------------------------------------------
cd "$DIR/00_prep"
log "00_prep: tleap"
__LEAP_BLOCK__
__HMR_BLOCK__
__RESTRAINER_BLOCK__
# -- 01_min -------------------------------------------------------------------
cd "$DIR/01_min"
log "01_min: starting"
cp "$DIR/00_prep/structure.rst7" structure_min_0.rst7

max_min_cycles=__MAXCAP__
conv_thresh=__CONVTHRESH__
converged_cycle=0

for ((i=1; i<=${max_min_cycles}; i++)); do
    log "01_min: cycle ${i}"
    pmemd.cuda -O -i min.in -o structure_min_${i}.out \\
                            -p ../00_prep/__TOPOLOGY__ \\
                            -c structure_min_$((i-1)).rst7 \\
                            -r structure_min_${i}.rst7 \\
                            -ref structure_min_$((i-1)).rst7

    min_rms=$(awk '/NSTEP[[:space:]]+ENERGY[[:space:]]+RMS[[:space:]]+GMAX/ {getline; print $3}' \\
                  structure_min_${i}.out | sort -g | head -n 1)
    converged=$(awk -v r="${min_rms:-9e99}" -v t="${conv_thresh}" \\
                'BEGIN {print (r+0 < t+0) ? 1 : 0}')

    if [ "${converged}" -eq 1 ]; then
        log "01_min converged at cycle ${i}"
        converged_cycle=${i}; break
    fi
done

if [ "${converged_cycle}" -gt 0 ]; then
    min_cycles=${converged_cycle}
else
    log "WARNING: 01_min did not converge in ${max_min_cycles} cycles."
    min_cycles=${max_min_cycles}
fi

# -- 02_heat ------------------------------------------------------------------
cd "$DIR/02_heat"
log "02_heat"
pmemd.cuda -O -i heat.in -o structure_heat.out \\
                          -p ../00_prep/__TOPOLOGY__ \\
                          -c "$DIR/01_min/structure_min_${min_cycles}.rst7" \\
                          -r structure_heat.rst7 \\
                          -x structure_heat.nc \\
                          -ref "$DIR/01_min/structure_min_${min_cycles}.rst7"

# -- 03_equil -----------------------------------------------------------------
cd "$DIR/03_equil"
log "03_equil: starting"
cp "$DIR/02_heat/structure_heat.rst7" structure_equil_0.rst7

for ((i=1; i<=6; i++)); do
    log "03_equil: cycle ${i}/6"
    pmemd.cuda -O -i equil_${i}.in -o structure_equil_${i}.out \\
                                   -p ../00_prep/__TOPOLOGY__ \\
                                   -c structure_equil_$((i-1)).rst7 \\
                                   -r structure_equil_${i}.rst7 \\
                                   -x structure_equil_${i}.nc \\
                                   -ref structure_equil_$((i-1)).rst7
done

# -- 04_NVT -------------------------------------------------------------------
cd "$DIR/04_NVT"
cp "$DIR/03_equil/structure_equil_6.rst7" structure_NVT_0.rst7
__NVT_LAUNCH__
"""

NVT_JOB_BODY = """\

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }

for ((i=__START__; i<=__END__; i++)); do
    log "NVT chunk ${i}/__TOTAL__"
    pmemd.cuda -O -i prod.in \\
                  -o structure_NVT_${i}.out \\
                  -p ../00_prep/__TOPOLOGY__ \\
                  -c structure_NVT_$((i-1)).rst7 \\
                  -r structure_NVT_${i}.rst7 \\
                  -x structure_NVT_${i}.nc
done
__NEXTJOB__"""


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def fill(template: str, **kwargs) -> str:
    for k, v in kwargs.items():
        template = template.replace(f"__{k}__", str(v))
    return template
